### ISSUE TITLE
Dart: Styleの遵守

### ISSUE THREAD

**Issue by fa0311** [YumNumm/EQMonitor#106]
[Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style) を遵守する

:(
![image](https://user-images.githubusercontent.com/34892635/183262688-312761ae-f7df-4187-98a6-588bed48280d.png)

**Comment by fa0311** [comment]
治してPullRequest送ろうと思ったけどFirebaseとかTokenとかでビルド通すのが面倒くさそうなので諦め

**Comment by YumNumm** [comment]
Issueありがとうございます。
早めに修正かけます…
