### ISSUE TITLE
[バグ] 通知設定画面のスイッチが隠れてしまう

### ISSUE THREAD

**Issue by beatbox4108** [YumNumm/EQMonitor#128]
画面を横向きにしたときに、「一番下のTTSによる読み上げ」の設定スイッチが保存ボタンに隠れて見えなくなってしまいます。
- 最新バージョンにおいて確認 (v0.6.0.r+381)

## 環境情報
バージョン: 0.6.0.r+381
OS: Android8.0.0
![image](https://user-images.githubusercontent.com/68136638/200981797-6abe4b88-6198-436c-b4b9-e4672bd06bbe.png)

**Comment by YumNumm** [comment]
Issueありがとうございます。
バグの確認をしました。

明日の夜にバグの修正を行い、
今週中に修正版のリリースを行う予定で進めていきます。

**Comment by YumNumm** [comment]
fixed: 44d75541b698b98cb2366a85dbc6e73414f5c0d8
