### ISSUE TITLE
[UI] 通知設定 保存ボタンとトグルボタンが重なる

### ISSUE THREAD

**Issue by Mogyuchi** [YumNumm/EQMonitor#213]
![E4078886-EE23-4FD9-BF80-F1A180E009C1](https://user-images.githubusercontent.com/69337624/211805299-c25add7d-f8bf-4fe1-b9b3-07f848bd8eb0.png)

**Comment by YumNumm** [comment]
ありがとうございます!
読み上げ設定の下に余白を入れるように改善しようと思います!
明日直したビルドを行います

**Comment by YumNumm** [comment]
fixed: 44d75541b698b98cb2366a85dbc6e73414f5c0d8
