### ISSUE TITLE
[バグ] 画面を横向きにして起動するとアプリアイコンが切り取られて表示されてしまう。

### ISSUE THREAD

**Issue by beatbox4108** [YumNumm/EQMonitor#41]
- [x] Androidバージョン8.0.0で確認しています。
- [x] アプリバージョンは EQMonitor (Build 0.2.3.r - 64)

具体的には、画面の縦横比が横のほうが大きくなった時に、アプリアイコンがはみ出してしまいます。

**Comment by YumNumm** [comment]
Issueありがとうございます
アプリ起動時のスプラッシュ画面のことでしょうか
不具合確認しました
