### ISSUE TITLE
[バグ]震度アイコンが正常に表示されない不具合

### ISSUE THREAD

**Issue by beatbox4108** [YumNumm/EQMonitor#48]
- [ ] EQMonitor (Build 0.2.3r - 64)で確認。
- [ ] 該当アイコンは震度5弱。
- [ ] 再起動を試しました
## 該当画像
![Screenshot_20220522-122913.jpg](https://user-images.githubusercontent.com/68136638/169677175-c7a86cee-37dd-4070-95d9-b28ed2e9e0ee.jpg)

**Comment by YumNumm** [comment]
Issueありがとうございます
この問題については、過去のリリース[v0.2.7-alpha](https://github.com/EQMonitor/EQMonitor/releases/tag/v0.2.7-alpha)で解決済みとなっています。
アップデートしていただけると幸いです。
