### ISSUE TITLE
iOS向けにビルドすると、pod installでコケる

### ISSUE THREAD

**Issue by Steve-0628** [YumNumm/EQMonitor#9]
`flutter build ios`や`flutter build ipa`をすると`awesome_notifications`周りが原因でpod installが止まってしまいます。

こちら https://github.com/rafaelsetragni/awesome_notifications/issues/232 に書いてあるような修正をすると、`pod install`を正常に実行できます。
具体的には、`ios/podfile`の一部を
```
platform :ios, '10.0'
```
に、`ios/Flutter/AppFrameworkInfo.plist`の一部を
```
<key>MinimumOSVersion</key>
<string>10.0</string>
```
に変更することで`pod install`が正常に実行できます。

**Comment by YumNumm** [comment]
iOS向けのビルド準備はまだできていないです…
今夜時間があったらやってみます! 

TODO:
- [ ] Podfile等のiOSバージョン修正
- [ ] Firebase構成ファイル準備
- [ ] 構成ファイルをCodeMagicで復元できるようにする
