### ISSUE TITLE
利用規約とLICENSEが矛盾している

### ISSUE THREAD

**Issue by nnn1590** [YumNumm/EQMonitor#98]
[LICENSE](https://github.com/EQMonitor/EQMonitor/blob/5cd7344b6833aac19140e4501478b487c63dacdb/LICENSE)はMIT/X11ライセンスとなっており、改変・再配布などが認められていますが
[利用規約](https://github.com/EQMonitor/EQMonitor/blob/5cd7344b6833aac19140e4501478b487c63dacdb/docs/policy.md)では
> ## 7. 禁止行為
> - 本アプリを逆アセンブル、逆コンパイル、リバースエンジニアリングする行為、及び本アプリのソースコードを解析しようと試みる行為
> - 本アプリにコードを注入する行為
> - 本アプリを複製、送信、譲渡、貸与または改変する行為

となっていて、改変・再配布・ソースコードの参照などができなくなっています（かつOSSではなくなっています）

**Comment by YumNumm** [comment]
ご指摘ありがとうございます。
利用規約について当該箇所を修正しました。
#99
